# Acrobot-v1

In [1]:
import numpy as np
import gym

from keras.models import Sequential
from keras.layers import Dense, Activation, Flatten
from keras.optimizers import Adam

from rl.agents.dqn import DQNAgent
from rl.policy import BoltzmannQPolicy, EpsGreedyQPolicy
from rl.memory import SequentialMemory


ENV_NAME = 'Acrobot-v1'
env = gym.make(ENV_NAME)


Using TensorFlow backend.


In [2]:
## play for rondom action, without being trained
for i_episode in range(5):
    observation = env.reset()
    for t in range(100):
        env.render()
        print(observation)
        action = env.action_space.sample()
        observation, reward, done, info = env.step(action)
        if done:
            print("Episode finished after {} timesteps".format(t+1))
            break
env.close()

[ 9.99988758e-01  4.74168905e-03  9.98327912e-01  5.78046712e-02
 -2.71179543e-02 -2.58458514e-04]
[ 0.99991258 -0.0132223   0.99627362  0.08624889 -0.1477931   0.277364  ]
[ 0.99969285 -0.02478329  0.99552583  0.09448976  0.03447288 -0.19723403]
[ 0.99963763 -0.02691845  0.99688048  0.07892601 -0.05576091  0.04312233]
[ 0.99980813 -0.01958853  0.9991132   0.04210478  0.12623823 -0.40414481]
[ 0.99998196 -0.00600612  0.99997592 -0.00693925  0.005491   -0.07620488]
[ 0.99996118  0.00881086  0.99844748 -0.05570134  0.13792198 -0.40055119]
[ 0.99946766  0.03262512  0.99212545 -0.12524814  0.0934004  -0.28247241]
[ 0.99952793  0.0307234   0.99162954 -0.12911566 -0.11182821  0.24323007]
[ 0.99986018  0.01672156  0.99487209 -0.10114115 -0.02462561  0.03158763]
[ 0.99998706 -0.00508628  0.99879085 -0.04916144 -0.18727159  0.47712743]
[ 0.99917291 -0.04066329  0.99892753  0.04630102 -0.15841838  0.45588138]
[ 0.99791069 -0.06460841  0.99222914  0.12442403 -0.07423148  0.31152701]
[ 0.99766433 

[ 0.9966069  -0.08230853  0.99998361 -0.0057254   0.46350452 -0.51258823]
[ 0.99999705  0.00243046  0.99723818 -0.07426988  0.36568069 -0.14896521]
[ 0.99835332  0.05736425  0.99828837 -0.05848351  0.17354339  0.31235444]
[0.9965586  0.08289118 0.99989878 0.01422747 0.07967232 0.40613809]
[0.99477629 0.10207904 0.99788969 0.06493199 0.11055969 0.09596087]
[ 0.99211975  0.12529323  0.99861273  0.05265569  0.11792802 -0.21301576]
[ 0.9927541   0.12016362  0.99861004  0.05270653 -0.16820263  0.21207176]
[ 0.99612228  0.08797953  0.99795366  0.06394129 -0.14860125 -0.10622535]
[ 0.99800103  0.06319771  0.99995251  0.00974557 -0.09668641 -0.43043224]
[ 0.9987567   0.04985034  0.9946647  -0.10316071 -0.0383716  -0.68214106]
[ 9.98918666e-01  4.64919248e-02  9.67998143e-01 -2.50957357e-01
 -1.79209476e-05 -7.94738738e-01]
[ 0.99886439  0.04764389  0.9170985  -0.39866068  0.00669406 -0.7432365 ]
[ 0.99938412  0.03509106  0.87330921 -0.48716632 -0.1301625  -0.23481906]
[ 0.99994715  0.01028059 

[ 0.99082255 -0.13516904  0.93697851  0.34938699 -1.1723919   1.70688508]
[ 0.9400811  -0.34095092  0.78985609  0.61329223 -0.90370187  1.25368272]
[ 0.89145976 -0.45309988  0.69155329  0.72232545 -0.29795228  0.19446564]
[ 0.8948882  -0.44629039  0.74174775  0.67067896  0.37348258 -0.90843353]
[ 0.95131837 -0.30820993  0.91325714  0.40738361  1.09191628 -2.2017741 ]
[ 0.99823337 -0.05941497  0.99720535 -0.07470939  1.37563663 -2.60625703]
[ 0.97644614  0.2157613   0.82884052 -0.55948494  1.31796922 -2.44058891]
[ 0.9131921   0.40752938  0.58433547 -0.8115122   0.67358464 -1.04960888]
[ 0.88732047  0.46115332  0.53402554 -0.84546834 -0.08718091  0.44653974]
[ 0.91829916  0.39588717  0.67580074 -0.73708436 -0.62371692  1.32209611]
[ 0.97441077  0.22477465  0.89578993 -0.44447768 -1.14355693  2.30011205]
[ 0.99961316 -0.02781238  0.99874563  0.05007155 -1.32923566  2.66663517]
[ 0.9629867  -0.26954892  0.85599762  0.51697975 -1.0561202   2.14046351]
[ 0.90371091 -0.42814318  0.61952834  

[ 0.99739427 -0.07214343  0.94636698 -0.3230937  -0.26910037  0.07949435]
[ 0.9942201  -0.10736108  0.94828323 -0.31742544 -0.07722602 -0.02650303]
[ 0.99342215 -0.11450949  0.95329611 -0.30203728  0.00704309  0.18476146]
[ 0.99453489 -0.10440472  0.96862285 -0.24853525  0.09355135  0.3653294 ]
[ 0.99694172 -0.07814863  0.98658567 -0.16324434  0.16694535  0.49685224]
[ 0.99922478 -0.03936796  0.99837601 -0.05696793  0.2171252   0.56048301]
[0.99980224 0.01988693 0.99978734 0.02062198 0.36602299 0.21140257]
[0.99609923 0.08824011 0.99799426 0.06330455 0.30623074 0.21882901]
[0.9905088  0.13744935 0.99406438 0.10879342 0.18056484 0.23762658]
[ 0.98535545  0.17051284  0.99239915  0.12306064  0.14755748 -0.0907269 ]
[ 0.98118848  0.19305224  0.99712671  0.07575167  0.07578102 -0.37335974]
[ 0.98506954  0.17215693  0.99882121  0.04854068 -0.28447699  0.10130054]
[ 0.99514535  0.09841612  0.99702615  0.077064   -0.44388211  0.16772739]
[ 0.99999485  0.00321043  0.99421823  0.10737836 -0.4893

[ 0.9560464  -0.29321542  0.63457419  0.77286196 -0.95256208  1.27597169]
[ 0.90216641 -0.43138819  0.49393305  0.86949994 -0.50548861  0.40816354]
[ 0.89131831 -0.45337807  0.55369728  0.83271803  0.26953003 -1.11176021]
[ 0.93937368 -0.34289515  0.80047659  0.59936402  0.91761186 -2.26742512]
[ 0.99289774 -0.11897093  0.99436809  0.10598158  1.32541148 -2.97197319]
[ 0.98936552  0.14545056  0.88821652 -0.45942509  1.24565473 -2.70077814]
[ 0.93836127  0.34565609  0.60232818 -0.79824856  0.78455239 -1.70170346]
[ 0.90477851  0.42588243  0.43889347 -0.8985391   0.07814868 -0.21280457]
[ 0.92722264  0.37451058  0.5325241  -0.84641484 -0.63283372  1.28112235]
[ 0.9792574   0.20262021  0.8020691  -0.59723125 -1.13559974  2.365621  ]
[ 0.99797426 -0.063619    0.99793649 -0.0642087  -1.46899184  3.25132308]
[ 0.94115587 -0.33797283  0.8352468   0.54987525 -1.25199582  3.03325988]
[ 0.86471002 -0.50227142  0.48179463  0.87628417 -0.53462938  1.77782448]
[ 0.85485534 -0.5188664   0.30548036  

In [4]:


# Get the environment and extract the number of actions.
np.random.seed(123)
env.seed(123)
nb_actions = env.action_space.n

model = Sequential()
model.add(Flatten(input_shape=(1,) + env.observation_space.shape))
model.add(Dense(300))
model.add(Activation('relu'))
model.add(Dense(300))
model.add(Activation('relu'))
model.add(Dense(300))
model.add(Activation('relu'))

model.add(Dense(nb_actions))
#
model.add(Activation('linear'))
print(model.summary())


_________________________________________________________________
Layer (type)                 Output Shape              Param #   
flatten_1 (Flatten)          (None, 6)                 0         
_________________________________________________________________
dense_1 (Dense)              (None, 300)               2100      
_________________________________________________________________
activation_1 (Activation)    (None, 300)               0         
_________________________________________________________________
dense_2 (Dense)              (None, 300)               90300     
_________________________________________________________________
activation_2 (Activation)    (None, 300)               0         
_________________________________________________________________
dense_3 (Dense)              (None, 300)               90300     
_________________________________________________________________
activation_3 (Activation)    (None, 300)               0         
__________

In [5]:

# # Finally, we configure and compile our agent. You can use every built-in Keras optimizer and
# # even the metrics!
memory = SequentialMemory(limit=50000, window_length=1)
policy = EpsGreedyQPolicy()
dqn = DQNAgent(model=model, nb_actions=nb_actions, memory=memory, nb_steps_warmup=50,
               target_model_update=200,train_interval=4, policy=policy)
dqn.compile(Adam(lr=1e-4), metrics=['mae'])
#
# # Okay, now it's time to learn something! We visualize the training here for show, but this
# # slows down training quite a lot. You can always safely abort the training prematurely using
# # Ctrl + C.
# dqn.fit(env, nb_steps=10000, visualize=False, verbose=2)
#
# # After training is done, we save the final weights.
# dqn.save_weights('dqn_{}_weights.h5f'.format(ENV_NAME), overwrite=True)

# Finally, evaluate our algorithm for 5 episodes.
#
weights_filename = 'dqn_{}_weights.h5f'.format(ENV_NAME)
#     # if args.weights:
#     #     weights_filename = args.weights
dqn.load_weights(weights_filename)
dqn.test(env, nb_episodes=10, visualize=True)
# dqn.test(env, nb_episodes=5, visualize=True)

Testing for 10 episodes ...
Episode 1: reward: -63.000, steps: 64
Episode 2: reward: -78.000, steps: 79
Episode 3: reward: -70.000, steps: 71
Episode 4: reward: -64.000, steps: 65
Episode 5: reward: -62.000, steps: 63
Episode 6: reward: -63.000, steps: 64
Episode 7: reward: -84.000, steps: 85
Episode 8: reward: -63.000, steps: 64
Episode 9: reward: -62.000, steps: 63
Episode 10: reward: -80.000, steps: 81


In [6]:
env.close()

## Research Infinite Solutions LLP

by [Research Infinite Solutions](http://www.researchinfinitesolutions.com/)
(https://busreservation.ris-ai.com/)
(https://www.bets-ai.com/)

Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.